### ISSUE TITLE
use native loops

### ISSUE THREAD

**Issue by jebeck** [tidepool-org/tideline#100]
As per @kentquirk's discovery of [this](http://jsperf.com/native-vs-array-js-vs-underscore/19), we'd like to use replace lodash `_.each()`, etc. with native loops to help optimize the speed of tideline rendering.

**Comment by TheLordHighExecutioner** [comment]
I'd love to help convert Underscore .each/.forEach into native forEach.

**Comment by jebeck** [comment]
Hi @TheLordHighExecutioner, this issue is very old and no longer reflects our current agreed-upon best practices—we are staying with lodash. Thanks for the offer!
